const username = [
  {
    id: "1",
    name: "Breno",
    age: "25",
    phone: "+123 123 123",
    email: "breno.sport@hotmail.com",
    username: "sbritobreno",
    password: "123",
    image: "https://griffinoffice.ie/wp-content/uploads/2015/06/Generic-Person-Image.png",
  },
  {
    id: "2",
    name: "Jeff",
    age: "25",
    phone: "+123 123 124",
    email: "jeff.sport@hotmail.com",
    username: "jefflima",
    password: "123",
    image: "https://griffinoffice.ie/wp-content/uploads/2015/06/Generic-Person-Image.png",
  },
];

const sports = [
  {
    id: "1",
    host: "sbritobreno",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Football_in_Bloomington%2C_Indiana%2C_1996.jpg",
    sport: "Voleyball",
    date: "Thrusday",
    time: "19:00",
    location: "Dublin 7",
    members: [{ user: "sbritobreno"}, { user: "jefflima"}],
    total_players: 10,
  },
  {
    id: "2",
    host: "sbritobreno",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Football_in_Bloomington%2C_Indiana%2C_1996.jpg",
    sport: "Voleyball",
    date: "Thrusday",
    time: "19:00",
    location: "Dublin 7",
    members: [{ user: "sbritobreno"}, { user: "jefflima"}],
    total_players: 10,
  },
  {
    id: "3",
    host: "sbritobreno",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Football_in_Bloomington%2C_Indiana%2C_1996.jpg",
    sport: "Voleyball",
    date: "Thrusday",
    time: "19:00",
    location: "Dublin 7",
    members: [{ user: "sbritobreno"}, { user: "jefflima"}],
    total_players: 10,
  },
  {
    id: "4",
    host: "sbritobreno",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Football_in_Bloomington%2C_Indiana%2C_1996.jpg",
    sport: "Football",
    date: "Thrusday",
    time: "19:00",
    location: "Dublin 7",
    members: [{ user: "sbritobreno"}, { user: "jefflima"}],
    total_players: 10,
  },
  {
    id: "5",
    host: "sbritobreno",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Football_in_Bloomington%2C_Indiana%2C_1996.jpg",
    sport: "Football",
    date: "Thrusday",
    time: "19:00",
    location: "Dublin 7",
    members: [{ user: "sbritobreno"}, { user: "jefflima"}],
    total_players: 10,
  },
  {
    id: "6",
    host: "sbritobreno",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Football_in_Bloomington%2C_Indiana%2C_1996.jpg",
    sport: "Football",
    date: "Thrusday",
    time: "19:00",
    location: "Dublin 7",
    members: [{ user: "sbritobreno"}, { user: "jefflima"}],
    total_players: 10,
  },
];

export { sports, username };
