const sports = [
    {
        "id": "1",
        "image": "https://upload.wikimedia.org/wikipedia/commons/a/ad/Football_in_Bloomington%2C_Indiana%2C_1996.jpg",
        "sport": "Futball",
        "date": "21/01/2023",
        "players": "7 players",
        "total": "10 players",
    },
    {
        "id": "2",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Carter_vs_Gasol%2C_Lakers_vs_Magic.jpg/640px-Carter_vs_Gasol%2C_Lakers_vs_Magic.jpg",
        "sport": "Basketball",
        "date": "21/01/2023",
        "players": "6 players",
        "total": "10 players",
    },
    {
        "id": "3",
        "image": "https://img.olympicchannel.com/images/image/private/t_social_share_thumb/f_auto/v1536936974/primary/exvzqcvorticinejmmel",
        "sport": "Voleyball",
        "date": "21/01/2023",
        "players": "3 players",
        "total": "10 players",
    },
    {
        "id": "1",
        "image": "https://upload.wikimedia.org/wikipedia/commons/a/ad/Football_in_Bloomington%2C_Indiana%2C_1996.jpg",
        "sport": "Futball",
        "date": "21/01/2023",
        "players": "7 players",
        "total": "10 players",
    },
    {
        "id": "2",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Carter_vs_Gasol%2C_Lakers_vs_Magic.jpg/640px-Carter_vs_Gasol%2C_Lakers_vs_Magic.jpg",
        "sport": "Basketball",
        "date": "21/01/2023",
        "players": "6 players",
        "total": "10 players",
    },
    {
        "id": "3",
        "image": "https://img.olympicchannel.com/images/image/private/t_social_share_thumb/f_auto/v1536936974/primary/exvzqcvorticinejmmel",
        "sport": "Voleyball",
        "date": "21/01/2023",
        "players": "3 players",
        "total": "10 players",
    },{
        "id": "3",
        "image": "https://img.olympicchannel.com/images/image/private/t_social_share_thumb/f_auto/v1536936974/primary/exvzqcvorticinejmmel",
        "sport": "Voleyball",
        "date": "21/01/2023",
        "players": "3 players",
        "total": "10 players",
    },
    {
        "id": "1",
        "image": "https://upload.wikimedia.org/wikipedia/commons/a/ad/Football_in_Bloomington%2C_Indiana%2C_1996.jpg",
        "sport": "Futball",
        "date": "21/01/2023",
        "players": "7 players",
        "total": "10 players",
    },
]

export {sports};